using System;
using System.Collections.Generic;

namespace InterrogationRoom.EasterEggs
{
    /// <summary>
    /// Pure deterministic selection. The supplied seed must be generated by the
    /// host specifically for public world content; never reuse a role seed.
    /// </summary>
    public static class EasterEggSelector
    {
        public const int DefaultSpawnChancePercent = 12;
        public const int MaximumSpawnChancePercent = 25;

        public static EasterEggSelection Select(
            int easterEggSeed,
            IReadOnlyList<EasterEggDefinition> authoredDefinitions,
            int spawnChancePercent = DefaultSpawnChancePercent)
        {
            if (authoredDefinitions == null)
                throw new ArgumentNullException(nameof(authoredDefinitions));
            if (authoredDefinitions.Count == 0 || spawnChancePercent <= 0)
                return EasterEggSelection.None;

            int cappedChance = Math.Min(spawnChancePercent, MaximumSpawnChancePercent);
            var random = new EasterEggRandom(easterEggSeed);
            if (random.Next(100) >= cappedChance)
                return EasterEggSelection.None;

            EasterEggDefinition selected = authoredDefinitions[random.Next(authoredDefinitions.Count)];
            if (selected == null)
                throw new ArgumentException("The authored catalog cannot contain null entries.", nameof(authoredDefinitions));
            return EasterEggSelection.Spawn(selected);
        }

        private struct EasterEggRandom
        {
            private uint state;

            public EasterEggRandom(int seed)
            {
                state = unchecked((uint)seed) ^ 0xC0FFEE11u;
                if (state == 0u)
                    state = 0x6D2B79F5u;
            }

            public int Next(int maximumExclusive)
            {
                if (maximumExclusive <= 0)
                    throw new ArgumentOutOfRangeException(nameof(maximumExclusive));

                uint value = state;
                value ^= value << 13;
                value ^= value >> 17;
                value ^= value << 5;
                state = value;
                return (int)(value % (uint)maximumExclusive);
            }
        }
    }
}
